### ISSUE TITLE
Make function to overwrite local json

### ISSUE THREAD

**Issue by mahadbajwa97** [BrentonCozby/ejs-sass-static-boilerplate#4]
Hello, I am working on ejs-sass boiler plate, I want to ask how/ where to add custom functions on server and execute them. I want to edit a json file from web frontend.

**Comment by BrentonCozby** [comment]
Hi @mahadbajwa97. That is outside the scope of this project, as this repo is meant only to get you started building a static website. I will say, however, that the pattern you're describing sounds very common (editing json data with user input) so you should be able to find a variety of methods online to do this. Best of luck.
